DROP TABLE IF EXISTS PATIENT;
CREATE TABLE PATIENT
(
	PT_ID CHAR(7) PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    DOB CHAR(10),
    INSURNACE VARCHAR(20)
);

DROP TABLE IF EXISTS NURSE;
CREATE TABLE NURSE
(
	EMPLOYEE_ID CHAR(2) PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20)
);

DROP TABLE IF EXISTS INVOICE;
CREATE TABLE INVOICE
(
	INVOICE_ID CHAR(7) PRIMARY KEY,
    INVOICE_DATE CHAR(10),
    PATIENT_ID CHAR(7),
    EMPLOYEE_ID CHAR(2)
);

DROP TABLE IF EXISTS INVOICE_LINE;
CREATE TABLE INVOICE_LINE
(
	INVOICE_ID CHAR(7),
    ITEM_ID CHAR(5),
    QUANTITY VARCHAR(2)
);
    
    